### ISSUE TITLE
Possible to "peak" at an input port / non-blocking receive?

### ISSUE THREAD

**Issue by tlrobinson** [jpaulm/jsfbp#19]
Is it possible to see which input ports have IPs ready to be received? Or to receive on multiple ports at the same time, and take whichever receives an IP first? (like `select` in POSIX sockets)

**Comment by alfa256** [comment]
I call this "peeking" and Paul doesn't seem to like it, but I do. I don't
like the idea of waiting on several ports, it defeats the simplicity of FBP
imho. A timed read should solve the issue, or peeking.

2015-02-14 0:11 GMT-03:00 Tom Robinson <notifications@github.com>:

**Comment by jpaulm** [comment]
Yes, @alfa256 is right - I don't like peeking!  I think it would also
"defeat the simplicity" of the FBP concept.  Also use the YAGNI concept -
do you have a use case?  If so, are you sure there is no way to handle it
using the existing facilities? Hope you are not still thinking
synchronously (horrors!) :-)

Re the other idea, we tried that many years ago - it was complex and not
robust.  It turns out that all you have to do is bring the different
streams (possibly with the IPs tagged to show origin) into one input port,
and handle them one at a time.
