### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by ComFreek** [jpaulm/jsfbp#8]
- `[variableName] = [value]` creates a global variable if `variableName` hasn't been declared before.
This pollutes the global namespace and should therefore be avoided. An example can be found in [fbp.js#19](https://github.com/jpaulm/jsfbp/blob/master/script/fbp.js#L19).

- Use `module.exports` instead of `exports`
Sources:
 - http://justbuildsomething.com/node-js-best-practices/#9
 - http://stackoverflow.com/a/7142924/603003
- "use strict" should be used (as in [this file](https://github.com/gulpjs/gulp-cli/blob/master/lib/completion.js))
- Maybe the code base would benefit from a JS dialect with a type system (e.g. [TypeScript](http://www.typescriptlang.org/)).

I would submit a PR for the first three things if you're okay with that.

**Comment by jpaulm** [comment]
Thanks for the "best practices" pointer, but it results in certain
questions!

I didn't realize that my "class" definitions should not go into the global
name space, but now I have to prefix all the exported class refs with
"fbp.", e.g. ;. 'sender" now becomes


 var fbp = require('./fbp.js');

exports.sender = function () {
var inport = fbp.InputPort.openInputPort('COUNT');
var outport = fbp.OutputPort.openOutputPort('OUT');
var ip = inport.receive();
var count = ip.contents;
fbp.IP.drop(ip);
//console.log(count);
for (var i = 0; i < count; i++) {
var ip = fbp.IP.create(i + '');
if (-1 == outport.send(ip))
return;;
}
}


Since this component is an "fbp component", I would like InputPort,
OutputPort and IP to just be able to stand on their own.  Does this make
sense?!  Having to add "fbp." in front of these symbols just seems to make
the API more complex - perhaps you can suggest a way around this...?

I'm not really making much use of classes - although they might be nice for
components...  Is TypeScript just an add-on, or will it block anything I'm
doing?

TIA,

Paul

**Comment by jpaulm** [comment]
I've made some changes to fbp.js, and added the following to each component:

var InputPort = fbp.InputPort;
var OutputPort = fbp.OutputPort;
var IP = fbp.IP;

So sender,js now looks like:

var fbp = require('./fbp.js');
var InputPort = fbp.InputPort;
var OutputPort = fbp.OutputPort;
var IP = fbp.IP;

exports.sender = function () {
    var inport = InputPort.openInputPort('COUNT'); 
    var outport = OutputPort.openOutputPort('OUT'); 
    var ip = inport.receive();
    var count = ip.contents;
    IP.drop(ip);
    //console.log(count);
    for (var i = 0; i < count; i++) {
      var ip = IP.create(i + ''); 
      if (-1 == outport.send(ip))
         return; 
    }   
  }

Is there a better way?!  Thanks!

**Comment by tlrobinson** [comment]
Those are basically the two options. The two styles aren't mutually exclusive, and the decision can be left up to the user of the API.

FYI, ES6 modules will make this much nicer by allowing you to do:

    import { IP, InputPort, OutputPort } from 'jsfbp';

 Or object destructuring syntax (similar in CoffeeScript) would let you do:

    var { IP: IP, InputPort: InputPort, OutputPort: OutputPort } = require("jsfbp");

**Comment by tlrobinson** [comment]
Also I've started moving in that direction: https://github.com/tlrobinson/jsfbp/commit/de77c619cc4772d5610b317d977369fcd4aa8310

I reworked `defProc` to accept either a module name as a string, or a function (the component) which the user has previously imported or defined in the same file as the network definition. It also takes the name from the function name if none is explicitly passed in.

I also started reorganizing the files into a more standard Node.js project style. The core library is in "index.js", and reusable components are in "components/*", and the fbptest*.js scripts have been moved to "examples/*".

If this looks good to you I'll go ahead and finish fixing the rest of the fbptest files.

**Comment by ComFreek** [comment]
```
var InputPort = fbp.InputPort;
var OutputPort = fbp.OutputPort;
var IP = fbp.IP;
```
This is one possible way, which you also mentioned.

Ideally, one would split the definition of InputPort, OutputPort and IP, so that the following becomes possible:
```
var InputPort = require('./InputPort'),
      OutputPort = require('./OutputPort'),
      IP = require('./IP');
```

TypeScript (TS) is a superset of JavaScript. Therefore, one needs to compile TS down to JS before being able to run the code.
The whole workflow can be simplified by using [Gulp](http://gulpjs.com/) (or similar JS build systems). It can watch for changes of TypeScript files and automatically recompile them.

As I said in the mailing list (JSFBP thread), JS has no built-in type checking at all. Variables are not typed. TS overcomes this problem by introducing types:
```
// JS: only run-time errors
var inport = fbp.InputPort.openInputPortTypo('COUNT');
inport.blub();

// TS: compile-time errors!
var inport = fbp.InputPort.openInputPortTypo('COUNT');
inport.blub();
```

ES6 can also be used by compiling it down to JS using Traceur or similar compilers. Unfortunately, ES 6 doesn't include a type system (ES 7 will maybe do so).
